core/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from django.views.decorators.http import require_POST

from .views import ProjectListView, ProjectDetailView

urlpatterns = patterns('',
                       url(r'^$', ProjectListView.as_view(), name='project-list'),
                       url(r'^project/(?P<pk>\d+)$', ProjectDetailView.as_view(), name='project-detail'),
)

project/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url, static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin_grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'', include('core.urls', namespace="core")),
                       url(r'', include('users.urls', namespace="users")),
) + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

users/urls.py
# coding: utf-8
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView


urlpatterns = patterns('',
                       url(r'^login/$', 'users.views.login', name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
import re

from django.conf import settings
from django.contrib import auth
from django.db import models
from django.core.cache import cache
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.text import capfirst
from django.core.mail import send_mail

from core.utils import validate_email

try:
    from django.utils.timezone import now as datetime_now
except ImportError:
    datetime_now = datetime.datetime.now

SHA1_RE = re.compile('^[a-f0-9]{40}$')


class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users must have an username')

        user = self.model(
            email=email,
            **extra_fields
        )
        user.set_password(password)
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        user.save(using=self._db)

        return user

    def create_superuser(self, password, email, **extra_fields):
        user = self.create_user(
            email=email,
            password=password,
            **extra_fields
        )
        user.is_active = True
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    objects = UserManager()

    email = models.EmailField(u'Email', db_index=True, unique=True)
    phone = models.CharField(u'Phone', max_length=30, blank=True, null=True)
    username = models.CharField(u'Юзернейм', max_length=71, blank=True, null=True)
    first_name = models.CharField(verbose_name=u'Имя', max_length=50)
    last_name = models.CharField(verbose_name=u'Фамилия', blank=True, null=True, max_length=50)

    is_active = models.BooleanField(u'Активен', default=False)
    is_admin = models.BooleanField(u'Персонал', default=False)
    created = models.DateTimeField(u'Дата создания', auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['created']

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.first_name and self.last_name:
            self.first_name = capfirst(self.first_name.lower())
            self.last_name = capfirst(self.last_name.lower())
        super(User, self).save(force_insert, force_update, using, update_fields)

    def get_full_name(self):
        if self.first_name == self.last_name:
            return self.get_short_name()
        return ' '.join([self.first_name, self.last_name])

    def get_short_name(self):
        return self.first_name

    def __unicode__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin

    def is_authenticated(self):
        return True

    def email_user(self, subject, message, from_email):
        if validate_email(self.email):
            send_mail(subject, message, from_email, [self.email])

    def last_login_strftime(self):
        if self.last_login:
            return self.last_login.strftime('%d/%m/%Y %H:%M')
        return ''

    def last_seen(self):
        return cache.get('seen_%s' % self)

    def is_online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            if now > self.last_seen() + datetime.timedelta(seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            else:
                return True
        else:
            return False


class Group(auth.models.Group):
    class Meta:
        proxy = True
        verbose_name = 'группа пользователей'
        verbose_name_plural = 'группы пользователей'

users/forms.py
# coding: utf-8
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password')


class ProfileAdminForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль', required=False,
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', required=False,
                                widget=forms.PasswordInput)

    class Meta:
        model = User

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 or password2:
            if not password1 == password2:
                raise forms.ValidationError('Введенные пароли не совпадают.')

users/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.views import logout as auth_logout
from django.contrib.auth import login as logon
from django.contrib.auth.backends import ModelBackend


def login(request):
    data = {}
    NEXT = request.GET.get('next')
    if NEXT:
        data['next'] = NEXT
    if request.method == "POST":
        next_url = request.POST.get('next')

        if request.user.is_authenticated():
            message = u'Вы уже авторизованы'
        else:
            email = request.POST.get('email')
            password = request.POST.get('password')
            backend = ModelBackend()
            user = backend.authenticate(email=email.lower(), password=password)
            if user is not None:
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                if user.is_active:
                    logon(request, user)
                    if next_url:
                        return redirect(next_url)
                    return redirect(reverse('core:project-list'))
                else:
                    message = u'Ваш аккаунт неактивен'
            else:
                if next_url:
                    data['next'] = next_url
                message = u'Пожалуйста правильность введенных данных'
        try:
            data['message'] = message
        except UnboundLocalError:
            pass
    return render(request, 'users/login.html', data)


def logoutAction(request, next_page='/'):
    language = None
    if hasattr(request, 'session'):
        if 'django_language' in request.session:
            language = request.session['django_language']
    response = auth_logout(request, next_page)
    if language:
        request.session['django_language'] = language
    return response

users/templates/users/login.html
{% extends 'core/base.html' %}

{% block content %}

    <div class="login-screen">
        <div class="container login">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="login-icon">
                                <img src="{{ STATIC_URL }}img/icons/png/Pensils.png">
                                <h4>Добро пожаловать</h4>
                            </div>
                        </div>
                        <div class="col-sm-9">
                            <form method="POST" action="{% url 'users:login' %}">
                                {% csrf_token %}
                                <div class="login-form">
                                    {% if message %}
                                        <p id="error-msg">{{ message }}</p>
                                    {% endif %}
                                    <div class="form-group">
                                        <input type="text" class="form-control login-field" value=""
                                               name="email"
                                               placeholder="Ваш email"
                                               id="login-name">
                                        <label class="login-field-icon fui-user" for="login-name"></label>
                                    </div>

                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control login-field" value="" placeholder="Пароль"
                                               id="login-pass">
                                        <label class="login-field-icon fui-lock" for="login-pass"></label>
                                    </div>
                                    <input type="hidden" name="next" value="{{ next }}">

                                    <button type="submit" class="btn btn-primary btn-lg btn-block">Войти</button>
                                    {#                                <a class="login-link" href="#">Lost your password?</a>#}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}